# Generated by Django 3.0.4 on 2020-03-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200321_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
