# Generated by Django 3.0.4 on 2020-03-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
