# Generated by Django 3.0.4 on 2020-03-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='entry',
        ),
    ]
