# Generated by Django 3.0.4 on 2020-03-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0004_auto_20200320_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
