# Generated by Django 3.0.4 on 2020-03-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0007_auto_20200323_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
