# Generated by Django 3.0.4 on 2020-03-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0011_auto_20200325_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
