# Generated by Django 3.0.4 on 2020-03-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0013_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
