# Generated by Django 3.0.4 on 2020-03-26 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app1', '0016_auto_20200326_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.ManyToManyField(blank=True, default='1', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
