# Generated by Django 3.0.4 on 2020-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0018_com_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
